version: "2"
linters:
  default: none
  enable:
    - errcheck
    - ineffassign
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - decorder
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - forcetypeassert
    - gochecknoinits
    - gocognit
    - goconst
    - godot
    - mnd
    - lll
    - makezero
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - paralleltest
    - reassign
    - revive
    - staticcheck
    - gosec
    - unconvert
    - unparam
    - whitespace
    - wsl_v5
    - wastedassign
    - dupl

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 2
      min-occurrences: 2
    nakedret:
      max-func-lines: 30
    nlreturn:
      block-size: 4
    nolintlint:
      require-explanation: true
      require-specific: true
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      enable:
        - err
      disable:
        - assign
        - decl
    gocognit:
      min-complexity: 20
    revive:
      rules:
        - name: use-any
        - name: unexported-naming
        - name: comment-spacings
        - name: enforce-repeated-arg-type-style
          arguments:
            - funcArgStyle: "full"
            - funcRetValStyle: "short"
  exclusions:
    paths-except:
      - example/

formatters:
  enable:
    - gofumpt
    - gci
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
    golines:
      max-len: 120
      chain-split-dots: true

